=== cervinkamichal0/XML_inzeraty/inzeraty.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://inzeraty.cerm47.cz"
    xmlns="http://inzeraty.cerm47.cz" elementFormDefault="qualified"
    xmlns:o="http://inzeraty.cerm47.cz" xmlns:vc="http://www.w3.org/2007/XMLSchema-versioning"
    vc:minVersion="1.1" xmlns:sch="http://purl.oclc.org/dsdl/schematron">

    <xs:element name="inzeraty" type="inzeratyType">
        
        <!--Zajištění unikátního ID pro inzeráty-->
        <xs:unique name="uniqueInzeratId">
            <xs:selector xpath="o:inzerat"/>
            <xs:field xpath="@id"/>
        </xs:unique>
        
       <!--Referenční integrita mezi seznamen kategorií a kategorií v inzerátu-->
        <xs:key name="kategorieKey">
            <xs:selector xpath="o:kategorie"/>
            <xs:field xpath="o:nazev"/>
        </xs:key>
        <xs:keyref name="kategorieRef" refer="kategorieKey">
            <xs:selector xpath="o:inzerat"/>
            <xs:field xpath="o:kategorie"/>
        </xs:keyref>
        
    </xs:element>


    <xs:complexType name="inzeratyType">
        <xs:sequence>
            <xs:element name="kategorie" type="kategorieType" maxOccurs="unbounded"/>
            <xs:element name="inzerat" type="inzeratType" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="kategorieType">
        <xs:sequence>
            <xs:element name="nazev" type="nonEmptyString"/>
            <xs:element name="popis" type="nonEmptyString"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="inzeratType">
        <xs:sequence>
            <xs:element name="nadpis" type="nonEmptyString" maxOccurs="1"/>
            <xs:element name="popis" type="xs:string" maxOccurs="1"/>
            <xs:choice>
                <xs:sequence>
                    <xs:element name="startovaciCena" type="xs:nonNegativeInteger"/>
                    <xs:element name="aktualniCena" type="xs:nonNegativeInteger"/>
                </xs:sequence>
                <xs:element name="cena" type="xs:nonNegativeInteger"/>
            </xs:choice>
            <xs:element name="mnozstvi" type="xs:integer"/>
            <xs:element name="kategorie" type="nonEmptyString"/>
            <xs:element name="prodavajici" type="prodavajiciType"/>
            <xs:element name="foto" type="xs:string"/>
            <xs:element name="datumNahrani" type="xs:date"/>
            <xs:choice>
                <xs:element name="datumKonce" type="xs:date"/>
                <xs:element name="rezervovano" type="xs:boolean"/>
            </xs:choice>
            <xs:element name="pocetZobrazeni" type="xs:nonNegativeInteger"/>
        </xs:sequence>
        <xs:attribute name="typ" type="typType"/>
        <xs:attribute name="id" type="xs:integer"/>
    </xs:complexType>

    <xs:simpleType name="typType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="prodej"/>
            <xs:enumeration value="aukce"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="prodavajiciType">
        <xs:sequence>
            <xs:element name="jmeno" type="nonEmptyString"/>
            <xs:element name="prijmeni" type="nonEmptyString"/>
            <xs:element name="telefon" type="cisloType"/>
            <xs:element name="email" type="emailType"/>
            <xs:element name="adresa" type="adresaType"/>
        </xs:sequence>
    </xs:complexType>

    <xs:simpleType name="cisloType">
        <xs:restriction base="xs:string">
            <xs:pattern value="[0-9]{9}"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="emailType">
        <xs:restriction base="xs:string">
            <xs:pattern value="[^@]+@[^\.]+\..+"/>
        </xs:restriction>
    </xs:simpleType>


    <xs:complexType name="adresaType">
        <xs:sequence>
            <xs:element name="mesto" type="xs:string"/>
            <xs:element name="psc" type="pscType"/>
            <xs:element name="ulice" type="xs:string"/>
            <xs:element name="cisloPopisne" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>

    <xs:simpleType name="pscType">
        <xs:restriction base="xs:string">
            <xs:pattern value="[0-9]{5}"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="nonEmptyString">
        <xs:restriction base="xs:string">
            <xs:minLength value="1" />
        </xs:restriction>
    </xs:simpleType>




<!--keyref na kategorie-->
    
    
</xs:schema>

=== cervinkamichal0/XML_inzeraty/inzeraty.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-model href="inzeraty.sch" type="application/xml" schematypens="http://purl.oclc.org/dsdl/schematron"?>
<inzeraty xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:schemaLocation="http://inzeraty.cerm47.cz inzeraty.xsd" xmlns="http://inzeraty.cerm47.cz"  
    >
    
    
    <kategorie>
        <nazev>Auto/Moto</nazev>
        <popis>Auta, motocykly, skútry, ...</popis>
    </kategorie>
    <kategorie>
        <nazev>Elektronika</nazev>
        <popis>Počitače, telefony, notebooky, tablety, spotřebiče, ...</popis>
    </kategorie>
    <kategorie>
        <nazev>Knihy</nazev>
        <popis>Knihy, časopisy, učebnice, skripta, ...</popis>
    </kategorie>
    <kategorie>
        <nazev>Oblečení</nazev>
        <popis>Boty, šperky, hodinky, doplňky, ...</popis>
    </kategorie>
    <kategorie>
        <nazev>Nábytek</nazev>
        <popis>Křesla, gauče, skříně, kuchyně, ...</popis>
    </kategorie>
    
    
    <inzerat typ="aukce" id="1">
        <nadpis>MacBook Air M2</nadpis>
        <popis>Prodám rok starý MacBook Air M2, záruka do 1.12.2024</popis>
        <startovaciCena>15000</startovaciCena>
        <aktualniCena>16000</aktualniCena>
        <mnozstvi>1</mnozstvi>
        <kategorie>Elektronika</kategorie>
        <prodavajici>
            <jmeno>Honza</jmeno>
            <prijmeni>Hrouda</prijmeni>
            <telefon>123456789</telefon>
            <email>honzahrouda@centrum.cz</email>
            <adresa>
                <mesto>Praha 5</mesto>
                <psc>15000</psc>
                <ulice>Preslova</ulice>
                <cisloPopisne>123</cisloPopisne>
            </adresa>
        </prodavajici>
        <foto>macbook_m2.jpg</foto>
        <datumNahrani>2024-03-29</datumNahrani>
        <datumKonce>2024-04-05</datumKonce>
        <pocetZobrazeni>120</pocetZobrazeni>
    </inzerat>

    <inzerat typ="prodej" id="2">
        <nadpis>BMW E90 320D</nadpis>
        <popis>Prodám auto BMW E90 320D, najeto 200 000km, bez závad, po rozvodech</popis>
        <cena>200000</cena>
        <mnozstvi>1</mnozstvi>
        <kategorie>Auto/Moto</kategorie>
        <prodavajici>
            <jmeno>Radek</jmeno>
            <prijmeni>Hrádek</prijmeni>
            <telefon>123345679</telefon>
            <email>radekhradek@gmail.com</email>
            <adresa>
                <mesto>Beroun</mesto>
                <psc>26601</psc>
                <ulice>Palouček</ulice>
                <cisloPopisne>123</cisloPopisne>
            </adresa>
        </prodavajici>
        <foto>e90_320d.jpg</foto>
        <datumNahrani>2024-04-01</datumNahrani>
        <rezervovano>false</rezervovano>
        <pocetZobrazeni>342</pocetZobrazeni>
    </inzerat>

    <inzerat typ="prodej" id="3">
        <nadpis>Zaklínač III: Krev elfů</nadpis>
        <popis>Prodám knihy Zaklínač III: Krev elfů, nové, nepoužité</popis>
        <cena>500</cena>
        <mnozstvi>5</mnozstvi>
        <kategorie>Knihy</kategorie>
        <prodavajici>
            <jmeno>Tomáš</jmeno>
            <prijmeni>Koláč</prijmeni>
            <telefon>123456789</telefon>
            <email>tomaskolac@seznam.cz</email>
            <adresa>
                <mesto>Plzeň</mesto>
                <psc>30100</psc>
                <ulice>Šumavská</ulice>
                <cisloPopisne>123</cisloPopisne>
            </adresa>
        </prodavajici>
        <foto>zaklinac.jpeg</foto>
        <datumNahrani>2024-04-02</datumNahrani>
        <rezervovano>false</rezervovano>
        <pocetZobrazeni>123</pocetZobrazeni>
    </inzerat>

    <inzerat typ="prodej" id="4">
        <nadpis>Boty Nike Air Max</nadpis>
        <popis>Prodám boty Nike Air Max, velikost 42, nové, nepoužité</popis>
        <cena>2000</cena>
        <mnozstvi>1</mnozstvi>
        <kategorie>Oblečení</kategorie>
        <prodavajici>
            <jmeno>Lucie</jmeno>
            <prijmeni>Nováková</prijmeni>
            <telefon>123456789</telefon>
            <email>lucienovakova@gmail.com</email>
            <adresa>
                <mesto>Brno</mesto>
                <psc>60200</psc>
                <ulice>Šumavská</ulice>
                <cisloPopisne>123</cisloPopisne>
            </adresa>
        </prodavajici>
        <foto>nike.jpg</foto>
        <datumNahrani>2024-04-03</datumNahrani>
        <rezervovano>false</rezervovano>
        <pocetZobrazeni>234</pocetZobrazeni>
    </inzerat>

    <inzerat typ="prodej" id="5">
        <nadpis>Stůl</nadpis>
        <popis>Prodám stůl, dubový, rozměry 120x80cm, nový</popis>
        <cena>5000</cena>
        <mnozstvi>1</mnozstvi>
        <kategorie>Nábytek</kategorie>
        <prodavajici>
            <jmeno>Josef</jmeno>
            <prijmeni>Novák</prijmeni>
            <telefon>123456789</telefon>
            <email>josefnovak@seznam.cz</email>
            <adresa>
                <mesto>Olomouc</mesto>
                <psc>77900</psc>
                <ulice>Šumavská</ulice>
                <cisloPopisne>123</cisloPopisne>
            </adresa>
        </prodavajici>
        <foto>stul.jpg</foto>
        <datumNahrani>2024-04-04</datumNahrani>
        <rezervovano>false</rezervovano>
        <pocetZobrazeni>345</pocetZobrazeni>
    </inzerat>

    <inzerat typ="prodej" id="6">
        <nadpis>Židle</nadpis>
        <popis>Prodám židle, 4 kusy, nové, nepoužité</popis>
        <cena>2000</cena>
        <mnozstvi>4</mnozstvi>
        <kategorie>Nábytek</kategorie>
        <prodavajici>
            <jmeno>Josef</jmeno>
            <prijmeni>Novák</prijmeni>
            <telefon>123456789</telefon>
            <email>josefnovak@seznam.cz</email>
            <adresa>
                <mesto>Olomouc</mesto>
                <psc>77900</psc>
                <ulice>Šumavská</ulice>
                <cisloPopisne>123</cisloPopisne>
            </adresa>
        </prodavajici>
        <foto>zidle.jpg</foto>
        <datumNahrani>2024-04-05</datumNahrani>
        <rezervovano>false</rezervovano>
        <pocetZobrazeni>456</pocetZobrazeni>
    </inzerat>

    <inzerat typ="prodej" id="7">
        <nadpis>Škoda Octavia 1.9 TDI</nadpis>
        <popis>Prodám auto Škoda Octavia 1.9 TDI, najeto 200 000km, bez závad, po rozvodech</popis>
        <cena>100000</cena>
        <mnozstvi>1</mnozstvi>
        <kategorie>Auto/Moto</kategorie>
        <prodavajici>
            <jmeno>Tomáš</jmeno>
            <prijmeni>Koláč</prijmeni>
            <telefon>123456789</telefon>
            <email>tomaskolac@seznam.cz</email>
            <adresa>
                <mesto>Plzeň</mesto>
                <psc>30100</psc>
                <ulice>Šumavská</ulice>
                <cisloPopisne>123</cisloPopisne>
            </adresa>
        </prodavajici>
        <foto>octavia.jpg</foto>
        <datumNahrani>2024-04-06</datumNahrani>
        <rezervovano>true</rezervovano>
        <pocetZobrazeni>567</pocetZobrazeni>
    </inzerat>

    <inzerat typ="aukce" id="8">
        <nadpis>MacBook Pro M1</nadpis>
        <popis>Prodám rok starý MacBook Pro M1, záruka do 1.12.2024</popis>
        <startovaciCena>20000</startovaciCena>
        <aktualniCena>21000</aktualniCena>
        <mnozstvi>1</mnozstvi>
        <kategorie>Elektronika</kategorie>
        <prodavajici>
            <jmeno>Honza</jmeno>
            <prijmeni>Hrouda</prijmeni>
            <telefon>123456789</telefon>
            <email>honzahrouda@centrum.cz</email>
            <adresa>
                <mesto>Praha 5</mesto>
                <psc>15000</psc>
                <ulice>Preslova</ulice>
                <cisloPopisne>123</cisloPopisne>
            </adresa>
        </prodavajici>
        <foto>macbook_pro_m1.jpg</foto>
        <datumNahrani>2024-03-16</datumNahrani>
        <datumKonce>2024-04-15</datumKonce>
        <pocetZobrazeni>678</pocetZobrazeni>
    </inzerat>
    
</inzeraty>
